# This file contains your private key.
# Do not give it away lightly!
Suite = "Ed25519"
Public = "eae3a4845f1fd4259cef6df1800381f2e0b41d341a994d07bcc8236aa4165994"
Private = "ba7fd580c687b7eeda5be015cc5f642c5dd8ace1ed23efb4b37058989e09400f"
Address = "tls://192.168.0.42:7010"
ListenAddress = ""
Description = "Conode_5"
WebSocketTLSCertificate = ""
WebSocketTLSCertificateKey = ""
